---
title: "EDLD651 Final Project"
author: "Dillon, Eliott, Simone"
date: "11/18/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(tidyverse)
library(rio)
library(here)
library(janitor)
library(RColorBrewer)
library(gtsummary)

pew <- haven::read_sav(here("data", "Pew Research Center Global Attitudes Summer 2020 Dataset - Public.sav")) %>% clean_names() %>% as_tibble()
```


```{r DillonChunkCleaning}
DillonPew <- pew
DillonPew$country <- characterize(DillonPew$country)


CovidChangeTable <- DillonPew %>% group_by(country, covid_change) %>% summarize(n=n()) %>% mutate(freq=n/sum(n))

ggplot(CovidChangeTable, aes(x = country, y = as.numeric(freq) ,fill=as.factor(covid_change))) +
  geom_bar(stat="identity")+
  coord_flip()

CovidChangeMeansTable <- DillonPew %>% select(country, covid_change) %>% pivot_wider(names_from = country, values_from = covid_change, values_fn = mean) %>% pivot_longer(cols=everything())

CovidLonger <- DillonPew %>% select(country, qs8, cregion_us) %>% filter(country=="United States" & !is.na(qs8)) %>% mutate(one = 1)
CovidLonger$qs8 <- characterize(CovidLonger$qs8)
CovidLonger$cregion_us <- characterize(CovidLonger$cregion_us) 
CovidLonger <- CovidLonger %>% pivot_wider(id_cols = c("cregion_us","qs8","one"),
                names_from = c("qs8","cregion_us"),
                values_from = "one",
                values_fn = list("one" = length))
CovidLonger <- CovidLonger %>% pivot_longer(cols=everything())


```

```{r EliottChunkCleaning}
#new df +  showing categories of interest as text
el_pew <- pew
el_pew$country <- characterize(el_pew$country)
el_pew$covid_ownfaith <- characterize(el_pew$covid_ownfaith)
el_pew$trust_people <- characterize(el_pew$trust_people)
el_pew$covid_change <- characterize(el_pew$covid_change)

#View(pew)
#View(el_pew)

#displaying variables of interest in a table
faith_table <- el_pew %>% 
  select(covid_ownfaith, trust_people, covid_change) %>% 
  group_by(trust_people, covid_ownfaith) %>% 
  filter(trust_people == "In general, most people can be trusted" | trust_people == "In general, most people cannot be trusted",
         covid_ownfaith == "Has not changed much" | covid_ownfaith == "Stronger" | covid_ownfaith == "Weaker") %>% 
  summarize(n=n()) %>% 
  mutate(percent = (n/sum(n))*100)
faith_table

#figure
el_pew %>% 
  filter(trust_people %in% c("In general, most people can be trusted", "In general, most people cannot be trusted")) %>%
  filter(trust_people == "In general, most people can be trusted" | trust_people == "In general, most people cannot be trusted",
         covid_ownfaith == "Has not changed much" | covid_ownfaith == "Stronger" | covid_ownfaith == "Weaker",
         covid_change == "A fair amount" | covid_change == "A great deal" | covid_change == "Not at all" | covid_change == "Not too much") %>% 
  ggplot() +
  (aes(x = covid_ownfaith, fill=as.factor(covid_change))) +
  geom_bar() +
  facet_wrap(~trust_people) +
  theme_bw() +
  scale_fill_brewer(palette="spectral") +
  labs(title = "Faith Change during COVID-19 Pandemic",
       subtitle = "by trust in people and amount of life change during the pandemic",
       x = "Faith Change",
       y = "Frequency",
       fill = "COVID Life Change") +
  coord_flip()

#displaying faith change with trust in people
faith_table_wider <- el_pew %>% 
  select(covid_ownfaith, covid_change, trust_people) %>% 
  filter(trust_people == "In general, most people can be trusted" | trust_people == "In general, most people cannot be trusted",
         covid_ownfaith == "Has not changed much" | covid_ownfaith == "Stronger" | covid_ownfaith == "Weaker") %>% 
  pivot_wider(names_from = covid_ownfaith, values_from = covid_change)
faith_table_wider

#I haven't used pivot_longer...not sure what to do with that here
```


```{r SimoneChunkCleaning}

characterize(pew)

#Setting up data and characterizing
sm_pew <- pew %>%
  mutate(covid_united = na_if(covid_united, 8),
         covid_united = na_if(covid_united, 9),
         covid_family = na_if(covid_family, 7),
         covid_family = na_if(covid_family, 8),
         covid_family = na_if(covid_family, 9))

sm_pew$country <- characterize(sm_pew$country)
sm_pew$sex <- characterize(sm_pew$sex)
sm_pew$covid_united <- characterize(sm_pew$covid_united)
sm_pew$covid_family <- characterize(sm_pew$covid_family) 

#Summary table of national unity percentages

sm_pew %>%
  select(country, covid_united) %>%
  tbl_summary(
    by = covid_united) 

#summary table of family closeness percentages

sm_pew %>%
  select(country, covid_family) %>%
  tbl_summary(
    by = covid_family)

# Figure for descriptive of changes in family closeness per country

sm_pew %>%
  select(country, covid_family)%>%
  drop_na(covid_family) %>%
  ggplot(aes(x = fct_infreq(country), fill=as.factor(covid_family))) +
  geom_bar() +
  theme_bw() +
  scale_fill_brewer(palette="spectral") +
  coord_flip() +
   labs(title = "Global Beliefs about Changes in Family Closeness Due to Covid",
       x = "Country",
       y = "Frequency", 
       fill = "Change in Family Closeness")

# Figure for descriptive of changes in perceptions of unity/division per country

sm_pew %>%
   select(country, covid_united)%>%
  drop_na(covid_united) %>%
  ggplot(aes(x = fct_infreq(country), fill=as.factor(covid_united))) +
  geom_bar() +
  theme_bw() +
  scale_fill_brewer(palette="spectral") +
  coord_flip() +
   labs(title = "Global Beliefs about Perceptions of National Unity or Division Due to Covid",
       x = "Country",
       y = "Frequency", 
       fill = "National Unity")


#Figure for global level of feelings of closeness to family due to COVID for those who feel country is more divided or united 

sm_pew %>%
   select(country, sex, covid_united, covid_family)%>%
  drop_na(covid_united, covid_family) %>%
  ggplot(aes(x = fct_reorder(country, covid_family), fill=as.factor(covid_family))) +
  geom_bar() +
  facet_wrap(~covid_united) +
  theme_bw() +
  scale_fill_brewer(palette="spectral") +
  coord_flip() +
   labs(title = "Global Beliefs about Changes in Family Closeness Due to Covid",
        subtitle = "Differences According to Perceptions of National Unity",
       x = "Country",
       y = "Frequency", 
       fill = "Change in Family Closeness") +
  theme(strip.text.x = element_text(size = 15, colour = "lightskyblue4")) +
  theme(strip.background =element_rect(fill="white"))


#Figure for level of belief about unity/division and perceptions of family closeness for men and women in the US

sm_pew %>%
   select(country, sex, covid_united, covid_family) %>%
  filter(country == "United States") %>%
  drop_na(covid_united, covid_family) %>%
  ggplot(aes(x = sex, fill=as.factor(covid_family))) +
  geom_bar(postion = "dodge") +
  facet_wrap(~covid_united) +
  theme_bw() +
  scale_fill_brewer(palette="spectral") +
   labs(title = "Beliefs about Changes to Family Closeness due to COVID in the US",
        subtitle = "Differences According to Perceptions of National Unity and Sex",
       x = "Sex",
       y = "Frequency", 
       fill = "Change in Family Closeness")

#Comparing USA and S Korea perceptions of Unity/division and family closeness due to covid (i.e. individualistic vs. more collectivistic)

sm_pew %>%
   select(country, covid_united, covid_family) %>%
  filter(country == "South Korea" | country == "United States") %>%
  drop_na(covid_united, covid_family) %>%
  ggplot(aes(x = country, fill=as.factor(covid_family))) +
  geom_bar() +
  facet_wrap(~covid_united) +
  theme_bw() +
  scale_fill_brewer(palette="spectral") +
   labs(title = "Beliefs about Changes to Family Closeness due to COVID in the USA vs. South Korea",
        subtitle = "Differences According to Perceptions of National Unity",
       x = "Country",
       y = "Frequency", 
       fill = "Change in Family Closeness") +
  theme(strip.text.x = element_text(size = 15, colour = "lightskyblue4")) +
  theme(strip.background =element_rect(fill="white"))


```


